# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 22:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('user',),
                'verbose_name': 'Collaborator',
                'verbose_name_plural': 'Collaborators',
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-create_date',), 'verbose_name': 'Project', 'verbose_name_plural': 'Project'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='content',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='', max_length=4000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collaborator',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
