# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-13 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='ela_directory_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
