# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 05:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20170107_0456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcomment',
            options={'ordering': ('date',), 'verbose_name': 'Project Comment', 'verbose_name_plural': 'Project Comments'},
        ),
    ]
