# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20170131_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='device_pictures/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('alt_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('date',),
                'verbose_name': 'Device Image',
                'verbose_name_plural': 'Device Images',
            },
        ),
        migrations.RemoveField(
            model_name='device',
            name='picture',
        ),
        migrations.AddField(
            model_name='deviceimage',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device'),
        ),
    ]
