# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20170122_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='picture',
            field=models.ImageField(null=True, upload_to='device_pictures/'),
        ),
    ]
