# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='device_pictures/'),
        ),
    ]
