# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='identification',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
