# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='url',
            field=models.URLField(),
        ),
    ]
