# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20161230_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
