# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_profile_linkedin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
