# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20170206_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='identification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
