# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='requestor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='desciption',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
