# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_repository_ela_directory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='user',
        ),
        migrations.DeleteModel(
            name='Repository',
        ),
    ]
