# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20170104_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='device',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='manager',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Lab',
        ),
    ]
