# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-06 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20170312_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=500)),
                ('wikipedia_url', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('established', models.IntegerField(default=2017)),
            ],
        ),
    ]
