# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-06 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='established',
            field=models.CharField(default='2017', max_length=5),
        ),
    ]
